import csv
from os import walk

f_all = []

# Make a list of files generated by proc-browser, one for each company
for (dirpath, dirnames, filenames) in walk('proc-browser'):
    f_all.extend(filenames)
    break

# all tweets file
# f_t = open('proc-merge/ALLTWEETS.csv', 'wb') This causes problems in Python 3
f_t = open('proc-merge/ALLTWEETS.csv', 'w', newline='')
c_t = csv.writer(f_t)  # Pen for all tweets

header_written = False
summary = []

# The file names generated by api and browser are the same so this is ok
for f in f_all:
    if f[0] == '.':  # This is a filer for (possibly hidden) system files
        continue
    f_a = open('proc-api/' + f)
    c_a = csv.reader(f_a)  # Pen for api tweets
    f_b = open('proc-browser/' + f)
    c_b = csv.reader(f_b)  # Pen for browser tweets

    header = next(c_a)
    next(c_b)

    entries = {}
    for entry in c_a:
        entries[entry[1]] = entry

    for entry in c_b:
        entries[entry[1]] = entry

    f_a.close()
    f_b.close()

    entries = [entries[entry] for entry in entries]
    entries = sorted(entries, key=lambda x: int(x[1]))

    f_m = open('proc-merge/' + f, 'w', newline='')
    c_m = csv.writer(f_m)
    c_m.writerow(header)
    c_m.writerows(entries)
    f_m.close()

    if not header_written:
        c_t.writerow(header)
        header_written = False
    c_t.writerows(entries)

    summary.append([f[:-4], len(entries)])

f_t.close()

# write summary
f_s = open('proc-merge/SUMMARY.csv', 'w', newline='')
c_s = csv.writer(f_s)
c_s.writerow(['user', 'tweets'])
c_s.writerows(summary)
f_s.close()
